# 手動実行の場合はデフォルトでテストしか行わない。デプロイまで行いたい場合はメニューのチェックを付ける
# それ以外のイベントではデプロイまで行う
name: demo-1_jobsplit-with-needs

on:
  release:
    types: [created]
  workflow_dispatch:
    # 手動実行する場合の入力パラメータ定義
    inputs:
      testOnly:
        type: boolean
        required: true
        default: true
        description: "Check to run tests only"
  push:

jobs:
  # build-testジョブは常に実行される
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  # deployジョブは inputs.testOnly が true じゃなく、
  # かつ先行ジョブが完了してから実行される
  deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.testOnly != true }} # inputs.testOnly が true じゃなく
    needs: build-test                  # build-testジョブが完了してから
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -DskipTests=true
      env:
        GITHUB_TOKEN: ${{ github.token }}
